### ISSUE TITLE
Fix console errors

### ISSUE THREAD

**Issue by oliward** [develop-me/git-simple#330]
<img width="921" alt="google chromegitsimple developme trainingscreen shot 31 oct 2017 at 09 51 06" src="https://user-images.githubusercontent.com/2562719/32217824-0ea32c90-be21-11e7-8b86-aa85a26c8b9c.png">

**Comment by arthurg90** [comment]
-js error is in the original bootstrap.js file (nobody has modified it)
-image error fixed

**Comment by arthurg90** [comment]
image issue fixed
olly fixed merge error w/js
