### ISSUE TITLE
Homepage featurettes

### ISSUE THREAD

**Issue by oliward** [develop-me/git-simple#39]
Each should be technology with icon and blurb:

- HTML5
- CSS3
- JS12

**Comment by oliward** [comment]
@OwenLD make images available for others. 
<img width="921" alt="google chrome - github com - - screen shot 14 nov 2016 16 41 05" src="https://cloud.githubusercontent.com/assets/2562719/20273428/23edb356-aa89-11e6-9a85-fe5bdd59bfc0.png">

**Comment by teapotnick** [comment]
Please remove me from your git chain 
Nick Clemas . Head of E-commerce

01460 281 865
07540 688 136
www.teapotcreative.co.uk

Teapot Creative Ltd . The Courtyard . Bowdens Farm . Hambridge . Somerset . TA10 0BP
Registered in England & Wales . Company No. 7945108

**Comment by oliward** [comment]
hi @teapotnick, you'll need to go here and change your status in top right to "Unwatch" to stop getting notifications as you have subscribed to these on GitHub:

`https://github.com/watching`

Cheers

**Comment by OwenLD** [comment]
image files added
